# Contenu du fichier DoxygenDocs.yml
name: Deploy Documentation

on:
  push:
    branches: [ AddBadges ]

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    needs: run-tests
    if: failure() # Ne s'exécute que si le job run-tests échoue
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          # These are default values, but included for clarity
          doxyfile-path: ./Doxyfile
          working-directory: .
      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html/docs
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: github-pages