# Contenu du fichier MavenDeploy.yml
name: Publish package to GitHub Packages

on:
  push:
    branches:
      - AddBadges

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: run-tests
    if: failure() # Ne s'exécute que si le job run-tests échoue
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}