name: Echo GitHub Token

on: [push]

jobs:
  echo_token:
    name: Echo GitHub Token
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GITHUB_TOKEN
