name: Run Tests, Ensure 80% Code Coverage, and Deploy Documentation

on:
  push:
    branches:
      - Master

jobs:
  run-tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Run tests with Maven
        run: mvn clean test
        continue-on-error: true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports/

      - name: Check if tests passed
        if: ${{ failure() }}
        run: exit 1

      - name: Run tests with Maven and generate coverage report
        run: mvn clean test jacoco:report

      - name: Upload code coverage report
        if: success() && steps.check-coverage.outputs.coverage_check_failed != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco/index.html

      - name: Check code coverage
        id: check-coverage
        run: mvn clean verify jacoco:report

  publish-package:
    needs: run-tests-and-coverage
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

  deploy-documentation:
    needs: run-tests-and-coverage
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          # These are default values, but included for clarity
          doxyfile-path: ./Doxyfile
          working-directory: .
      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html/docs
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: github-pages
